# Generated by Django 5.2 on 2025-04-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_ruleembedding_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='rule1',
            new_name='rule_1',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='rule2',
            new_name='rule_2',
        ),
        migrations.AddField(
            model_name='comparison',
            name='scenario',
            field=models.CharField(choices=[('same_doc', 'Same Document'), ('diff_doc', 'Different Document')], default='same_doc', max_length=20),
        ),
    ]
