# Generated by Django 5.2 on 2025-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_rename_rule1_comparison_rule_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='point_num',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
