# Generated by Django 5.2 on 2025-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_rule_point_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='point_num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='section_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
